### ISSUE TITLE
Error when mounting in the VM

### ISSUE THREAD

**Issue by wanzysky** [jtcriswell/csc256-mp2#1]
When mounting disks that are from the floppy directory, an error occurred:

`mount: can't read '/etc/fstab': No such file or directory` 

Also, the `umount` command seems not existing in the OpenWRT image.

**Comment by wanzysky** [comment]
Maybe related to this issue: https://dev.archive.openwrt.org/ticket/9322.html.

**Comment by wanzysky** [comment]
It seems the runqemu.sh must be used with the parameter, i.e, we should use `runqemu.sh path/to/image` while `runqemu.sh` doesn't work.

There are an additional option `-append "root=PARTUUID=076b2e55-02 rootfstype=ext4 rootwait console=tty0 console=ttyS0,38400n8 edd=off noinitrd"` for the first form.

**Comment by jtcriswell** [comment]
IIRC, the issue is that you need to boot with the newer Linux 5.x kernel that you compile in order to use the floppy device.
